/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BasicWorkspaceInfo {
    #[serde(rename = "url_slug")]
    pub url_slug: String,
    #[serde(rename = "estimate_scale")]
    pub estimate_scale: Vec<i64>,
}

impl BasicWorkspaceInfo {
    pub fn new(url_slug: String, estimate_scale: Vec<i64>) -> BasicWorkspaceInfo {
        BasicWorkspaceInfo {
            url_slug,
            estimate_scale,
        }
    }
}


