/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateEntityTemplate : Request paramaters for creating an entirely new entity template.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateEntityTemplate {
    /// The name of the new entity template
    #[serde(rename = "name")]
    pub name: String,
    /// The id of the user creating this template.
    #[serde(rename = "author_id", skip_serializing_if = "Option::is_none")]
    pub author_id: Option<uuid::Uuid>,
    #[serde(rename = "story_contents")]
    pub story_contents: Box<crate::models::CreateStoryContents>,
}

impl CreateEntityTemplate {
    /// Request paramaters for creating an entirely new entity template.
    pub fn new(name: String, story_contents: crate::models::CreateStoryContents) -> CreateEntityTemplate {
        CreateEntityTemplate {
            name,
            author_id: None,
            story_contents: Box::new(story_contents),
        }
    }
}


