/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateOrDeleteStoryReaction {
    /// The emoji short-code to add / remove. E.g. `:thumbsup::skin-tone-4:`.
    #[serde(rename = "emoji")]
    pub emoji: String,
}

impl CreateOrDeleteStoryReaction {
    pub fn new(emoji: String) -> CreateOrDeleteStoryReaction {
        CreateOrDeleteStoryReaction { emoji }
    }
}
