/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateLabelParams : Request parameters for creating a Label on a Shortcut Story.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateLabelParams {
    /// The name of the new Label.
    #[serde(rename = "name")]
    pub name: String,
    /// The description of the new Label.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The hex color to be displayed with the Label (for example, \"#ff0000\").
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    /// This field can be set to another unique ID. In the case that the Label has been imported from another tool, the ID in the other tool can be indicated here.
    #[serde(rename = "external_id", skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
}

impl CreateLabelParams {
    /// Request parameters for creating a Label on a Shortcut Story.
    pub fn new(name: String) -> CreateLabelParams {
        CreateLabelParams {
            name,
            description: None,
            color: None,
            external_id: None,
        }
    }
}


