/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateIteration {
    /// An array of UUIDs for any Members you want to add as Followers.
    #[serde(rename = "follower_ids", skip_serializing_if = "Option::is_none")]
    pub follower_ids: Option<Vec<uuid::Uuid>>,
    /// An array of UUIDs for any Groups you want to add as Followers. Currently, only one Group
    /// association is presented in our web UI.
    #[serde(rename = "group_ids", skip_serializing_if = "Option::is_none")]
    pub group_ids: Option<Vec<uuid::Uuid>>,
    /// An array of Labels attached to the Iteration.
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<Vec<crate::models::CreateLabelParams>>,
    /// The description of the Iteration.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The name of this Iteration.
    #[serde(rename = "name")]
    pub name: String,
    /// The date this Iteration begins, e.g. 2019-07-01.
    #[serde(rename = "start_date")]
    pub start_date: String,
    /// The date this Iteration ends, e.g. 2019-07-01.
    #[serde(rename = "end_date")]
    pub end_date: String,
}

impl CreateIteration {
    pub fn new(name: String, start_date: String, end_date: String) -> CreateIteration {
        CreateIteration {
            follower_ids: None,
            group_ids: None,
            labels: None,
            description: None,
            name,
            start_date,
            end_date,
        }
    }
}
