/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CustomFieldValueParams {
    /// The unique public ID for the CustomField.
    #[serde(rename = "field_id")]
    pub field_id: uuid::Uuid,
    /// The unique public ID for the CustomFieldEnumValue.
    #[serde(rename = "value_id")]
    pub value_id: uuid::Uuid,
    /// A literal value for the CustomField. Currently ignored.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl CustomFieldValueParams {
    pub fn new(field_id: uuid::Uuid, value_id: uuid::Uuid) -> CustomFieldValueParams {
        CustomFieldValueParams {
            field_id,
            value_id,
            value: None,
        }
    }
}


