/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// DataConflictError : Error returned when Datomic tx fails due to Datomc :db.error/cas-failed
/// error

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataConflictError {
    #[serde(rename = "error")]
    pub error: Error,
    /// An explanatory message: \"The update failed due to a data conflict. Please refresh and try
    /// again.\"
    #[serde(rename = "message")]
    pub message: String,
}

impl DataConflictError {
    /// Error returned when Datomic tx fails due to Datomc :db.error/cas-failed error
    pub fn new(error: Error, message: String) -> DataConflictError {
        DataConflictError { error, message }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "data-conflict-error")]
    DataConflictError,
}

impl Default for Error {
    fn default() -> Error {
        Self::DataConflictError
    }
}
