/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeleteStories {
    /// An array of IDs of Stories to delete.
    #[serde(rename = "story_ids")]
    pub story_ids: Vec<i64>,
}

impl DeleteStories {
    pub fn new(story_ids: Vec<i64>) -> DeleteStories {
        DeleteStories {
            story_ids,
        }
    }
}


