/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetMember {
    /// The unique ID of the Organization to limit the lookup to.
    #[serde(rename = "org-public-id", skip_serializing_if = "Option::is_none")]
    pub org_public_id: Option<uuid::Uuid>,
}

impl GetMember {
    pub fn new() -> GetMember {
        GetMember {
            org_public_id: None,
        }
    }
}


