/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetExternalLinkStoriesParams {
    /// The external link associated with one or more stories.
    #[serde(rename = "external_link")]
    pub external_link: String,
}

impl GetExternalLinkStoriesParams {
    pub fn new(external_link: String) -> GetExternalLinkStoriesParams {
        GetExternalLinkStoriesParams { external_link }
    }
}
