/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// HistoryReferenceStory : A reference to a Story.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HistoryReferenceStory {
    /// The ID of the entity referenced.
    #[serde(rename = "id")]
    pub id: serde_json::Value,
    /// The type of entity referenced.
    #[serde(rename = "entity_type")]
    pub entity_type: String,
    /// The application URL of the Story.
    #[serde(rename = "app_url")]
    pub app_url: String,
    /// The name of the entity referenced.
    #[serde(rename = "name")]
    pub name: String,
    /// If the referenced entity is a Story, either \"bug\", \"chore\", or \"feature\".
    #[serde(rename = "story_type")]
    pub story_type: StoryType,
}

impl HistoryReferenceStory {
    /// A reference to a Story.
    pub fn new(
        id: serde_json::Value,
        entity_type: String,
        app_url: String,
        name: String,
        story_type: StoryType,
    ) -> HistoryReferenceStory {
        HistoryReferenceStory {
            id,
            entity_type,
            app_url,
            name,
            story_type,
        }
    }
}

/// If the referenced entity is a Story, either \"bug\", \"chore\", or \"feature\".
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StoryType {
    #[serde(rename = "feature")]
    Feature,
    #[serde(rename = "chore")]
    Chore,
    #[serde(rename = "bug")]
    Bug,
}

impl Default for StoryType {
    fn default() -> StoryType {
        Self::Feature
    }
}
