/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// HistoryReferenceWorkflowState : A references to a Story Workflow State.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HistoryReferenceWorkflowState {
    /// The ID of the entity referenced.
    #[serde(rename = "id")]
    pub id: serde_json::Value,
    /// The type of entity referenced.
    #[serde(rename = "entity_type")]
    pub entity_type: String,
    /// Either \"unstarted\", \"started\", or \"done\".
    #[serde(rename = "type")]
    pub r#type: RHashType,
    /// The name of the entity referenced.
    #[serde(rename = "name")]
    pub name: String,
}

impl HistoryReferenceWorkflowState {
    /// A references to a Story Workflow State.
    pub fn new(
        id: serde_json::Value,
        entity_type: String,
        r#type: RHashType,
        name: String,
    ) -> HistoryReferenceWorkflowState {
        HistoryReferenceWorkflowState {
            id,
            entity_type,
            r#type,
            name,
        }
    }
}

/// Either \"unstarted\", \"started\", or \"done\".
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "started")]
    Started,
    #[serde(rename = "unstarted")]
    Unstarted,
    #[serde(rename = "done")]
    Done,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Started
    }
}
