/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// HistoryReferenceCommit : A reference to a VCS Commit.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HistoryReferenceCommit {
    /// The ID of the entity referenced.
    #[serde(rename = "id")]
    pub id: serde_json::Value,
    /// The type of entity referenced.
    #[serde(rename = "entity_type")]
    pub entity_type: String,
    /// The message from the Commit.
    #[serde(rename = "message")]
    pub message: String,
    /// The external URL for the Branch.
    #[serde(rename = "url")]
    pub url: String,
}

impl HistoryReferenceCommit {
    /// A reference to a VCS Commit.
    pub fn new(
        id: serde_json::Value,
        entity_type: String,
        message: String,
        url: String,
    ) -> HistoryReferenceCommit {
        HistoryReferenceCommit { id, entity_type, message, url }
    }
}
