/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// HistoryActionWorkspace2BulkUpdate : An action representing a bulk operation within a workspace2.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HistoryActionWorkspace2BulkUpdate {
    /// The ID of the entity referenced.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// The type of entity referenced.
    #[serde(rename = "entity_type")]
    pub entity_type: String,
    /// The action of the entity referenced.
    #[serde(rename = "action")]
    pub action: Action,
    /// The name of the workspace2 in which the BulkUpdate occurred.
    #[serde(rename = "name")]
    pub name: String,
}

impl HistoryActionWorkspace2BulkUpdate {
    /// An action representing a bulk operation within a workspace2.
    pub fn new(
        id: uuid::Uuid,
        entity_type: String,
        action: Action,
        name: String,
    ) -> HistoryActionWorkspace2BulkUpdate {
        HistoryActionWorkspace2BulkUpdate {
            id,
            entity_type,
            action,
            name,
        }
    }
}

/// The action of the entity referenced.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "bulk-update")]
    BulkUpdate,
}

impl Default for Action {
    fn default() -> Action {
        Self::BulkUpdate
    }
}
