/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// HistoryActionStoryDelete : An action representing a Story being deleted.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HistoryActionStoryDelete {
    /// The ID of the entity referenced.
    #[serde(rename = "id")]
    pub id: i64,
    /// The type of entity referenced.
    #[serde(rename = "entity_type")]
    pub entity_type: String,
    /// The action of the entity referenced.
    #[serde(rename = "action")]
    pub action: Action,
    /// The name of the Story.
    #[serde(rename = "name")]
    pub name: String,
    /// The type of Story; either feature, bug, or chore.
    #[serde(rename = "story_type")]
    pub story_type: StoryType,
}

impl HistoryActionStoryDelete {
    /// An action representing a Story being deleted.
    pub fn new(
        id: i64,
        entity_type: String,
        action: Action,
        name: String,
        story_type: StoryType,
    ) -> HistoryActionStoryDelete {
        HistoryActionStoryDelete {
            id,
            entity_type,
            action,
            name,
            story_type,
        }
    }
}

/// The action of the entity referenced.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "delete")]
    Delete,
}

impl Default for Action {
    fn default() -> Action {
        Self::Delete
    }
}
/// The type of Story; either feature, bug, or chore.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StoryType {
    #[serde(rename = "feature")]
    Feature,
    #[serde(rename = "chore")]
    Chore,
    #[serde(rename = "bug")]
    Bug,
}

impl Default for StoryType {
    fn default() -> StoryType {
        Self::Feature
    }
}
