/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// HistoryReferenceGroup : A reference to a Group.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HistoryReferenceGroup {
    /// The ID of the entity referenced.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// The type of entity referenced.
    #[serde(rename = "entity_type")]
    pub entity_type: String,
    /// The name of the entity referenced.
    #[serde(rename = "name")]
    pub name: String,
}

impl HistoryReferenceGroup {
    /// A reference to a Group.
    pub fn new(id: uuid::Uuid, entity_type: String, name: String) -> HistoryReferenceGroup {
        HistoryReferenceGroup { id, entity_type, name }
    }
}
