/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// Icon : Icons are used to attach images to Groups, Workspaces, Members, and Loading screens in
/// the Shortcut web application.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Icon {
    /// A string description of this resource.
    #[serde(rename = "entity_type")]
    pub entity_type: String,
    /// The unique ID of the Icon.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// The time/date that the Icon was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// The time/date that the Icon was updated.
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    /// The URL of the Icon.
    #[serde(rename = "url")]
    pub url: String,
}

impl Icon {
    /// Icons are used to attach images to Groups, Workspaces, Members, and Loading screens in the
    /// Shortcut web application.
    pub fn new(
        entity_type: String,
        id: uuid::Uuid,
        created_at: String,
        updated_at: String,
        url: String,
    ) -> Icon {
        Icon { entity_type, id, created_at, updated_at, url }
    }
}
