/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Identity : The Identity of the VCS user that authored the Commit.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Identity {
    /// A string description of this resource.
    #[serde(rename = "entity_type")]
    pub entity_type: String,
    /// This is your login in VCS.
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
    /// The type of Identity; currently only type is github.
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<String>,
}

impl Identity {
    /// The Identity of the VCS user that authored the Commit.
    pub fn new(entity_type: String, name: Option<String>, r#type: Option<String>) -> Identity {
        Identity {
            entity_type,
            name,
            r#type,
        }
    }
}


