/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListMembers {
    /// The unique ID of the Organization to limit the list to.
    #[serde(rename = "org-public-id", skip_serializing_if = "Option::is_none")]
    pub org_public_id: Option<uuid::Uuid>,
}

impl ListMembers {
    pub fn new() -> ListMembers {
        ListMembers { org_public_id: None }
    }
}
