/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListLabels {
    /// A true/false boolean indicating if the slim versions of the Label should be returned.
    #[serde(rename = "slim", skip_serializing_if = "Option::is_none")]
    pub slim: Option<bool>,
}

impl ListLabels {
    pub fn new() -> ListLabels {
        ListLabels { slim: None }
    }
}
