/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListGroupStories {
    /// The maximum number of results to return. (Defaults to 1000, max 1000)
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// The offset at which to begin returning results. (Defaults to 0)
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
}

impl ListGroupStories {
    pub fn new() -> ListGroupStories {
        ListGroupStories { limit: None, offset: None }
    }
}
