/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MemberInfo {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "mention_name")]
    pub mention_name: String,
    #[serde(rename = "workspace2")]
    pub workspace2: Box<crate::models::BasicWorkspaceInfo>,
}

impl MemberInfo {
    pub fn new(id: uuid::Uuid, name: String, mention_name: String, workspace2: crate::models::BasicWorkspaceInfo) -> MemberInfo {
        MemberInfo {
            id,
            name,
            mention_name,
            workspace2: Box::new(workspace2),
        }
    }
}


