/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// MilestoneStats : A group of calculated values for this Milestone.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MilestoneStats {
    /// The average cycle time (in seconds) of completed stories in this Milestone.
    #[serde(rename = "average_cycle_time", skip_serializing_if = "Option::is_none")]
    pub average_cycle_time: Option<i64>,
    /// The average lead time (in seconds) of completed stories in this Milestone.
    #[serde(rename = "average_lead_time", skip_serializing_if = "Option::is_none")]
    pub average_lead_time: Option<i64>,
    /// The number of related documents tp this Milestone.
    #[serde(rename = "num_related_documents")]
    pub num_related_documents: i64,
}

impl MilestoneStats {
    /// A group of calculated values for this Milestone.
    pub fn new(num_related_documents: i64) -> MilestoneStats {
        MilestoneStats {
            average_cycle_time: None,
            average_lead_time: None,
            num_related_documents,
        }
    }
}
