/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// StoryLink : Story links allow you create semantic relationships between two stories.
/// Relationship types are relates to, blocks / blocked by, and duplicates / is duplicated by. The
/// format is `subject -> link -> object`, or for example \"story 5 blocks story 6\".

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StoryLink {
    /// A string description of this resource.
    #[serde(rename = "entity_type")]
    pub entity_type: String,
    /// The unique identifier of the Story Link.
    #[serde(rename = "id")]
    pub id: i64,
    /// The ID of the subject Story.
    #[serde(rename = "subject_id")]
    pub subject_id: i64,
    /// The workflow state of the \"subject\" story.
    #[serde(rename = "subject_workflow_state_id")]
    pub subject_workflow_state_id: i64,
    /// How the subject Story acts on the object Story. This can be \"blocks\", \"duplicates\", or
    /// \"relates to\".
    #[serde(rename = "verb")]
    pub verb: String,
    /// The ID of the object Story.
    #[serde(rename = "object_id")]
    pub object_id: i64,
    /// The time/date when the Story Link was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// The time/date when the Story Link was last updated.
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl StoryLink {
    /// Story links allow you create semantic relationships between two stories. Relationship types
    /// are relates to, blocks / blocked by, and duplicates / is duplicated by. The format is
    /// `subject -> link -> object`, or for example \"story 5 blocks story 6\".
    pub fn new(
        entity_type: String,
        id: i64,
        subject_id: i64,
        subject_workflow_state_id: i64,
        verb: String,
        object_id: i64,
        created_at: String,
        updated_at: String,
    ) -> StoryLink {
        StoryLink {
            entity_type,
            id,
            subject_id,
            subject_workflow_state_id,
            verb,
            object_id,
            created_at,
            updated_at,
        }
    }
}
