/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// StoryHistoryChangeOldNewStr : A timestamp that represents the Story's deadline.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StoryHistoryChangeOldNewStr {
    /// The old value.
    #[serde(
        rename = "old",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub old: Option<Option<String>>,
    /// The new value.
    #[serde(rename = "new", skip_serializing_if = "Option::is_none")]
    pub new: Option<String>,
}

impl StoryHistoryChangeOldNewStr {
    /// A timestamp that represents the Story's deadline.
    pub fn new() -> StoryHistoryChangeOldNewStr {
        StoryHistoryChangeOldNewStr { old: None, new: None }
    }
}
