/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// StoryHistoryChangeOldNewBool : True if the Story has archived, otherwise false.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StoryHistoryChangeOldNewBool {
    /// The old value.
    #[serde(rename = "old", skip_serializing_if = "Option::is_none")]
    pub old: Option<bool>,
    /// The new value.
    #[serde(rename = "new", skip_serializing_if = "Option::is_none")]
    pub new: Option<bool>,
}

impl StoryHistoryChangeOldNewBool {
    /// True if the Story has archived, otherwise false.
    pub fn new() -> StoryHistoryChangeOldNewBool {
        StoryHistoryChangeOldNewBool {
            old: None,
            new: None,
        }
    }
}


