/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// StoryReaction : Emoji reaction on a comment.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StoryReaction {
    /// Emoji text of the reaction.
    #[serde(rename = "emoji")]
    pub emoji: String,
    /// Permissions who have reacted with this.
    #[serde(rename = "permission_ids")]
    pub permission_ids: Vec<uuid::Uuid>,
}

impl StoryReaction {
    /// Emoji reaction on a comment.
    pub fn new(emoji: String, permission_ids: Vec<uuid::Uuid>) -> StoryReaction {
        StoryReaction { emoji, permission_ids }
    }
}
