/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// StoryHistoryChangeOldNewInt : The estimate value for the Story



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StoryHistoryChangeOldNewInt {
    /// The old value.
    #[serde(rename = "old", skip_serializing_if = "Option::is_none")]
    pub old: Option<i64>,
    /// The new value.
    #[serde(rename = "new", skip_serializing_if = "Option::is_none")]
    pub new: Option<i64>,
}

impl StoryHistoryChangeOldNewInt {
    /// The estimate value for the Story
    pub fn new() -> StoryHistoryChangeOldNewInt {
        StoryHistoryChangeOldNewInt {
            old: None,
            new: None,
        }
    }
}


