/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// StoryContents : A container entity for the attributes this template should populate.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StoryContents {
    /// The description of the story.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// A string description of this resource.
    #[serde(rename = "entity_type", skip_serializing_if = "Option::is_none")]
    pub entity_type: Option<String>,
    /// An array of labels attached to the story.
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<Vec<crate::models::LabelSlim>>,
    /// The type of story (feature, bug, chore).
    #[serde(rename = "story_type", skip_serializing_if = "Option::is_none")]
    pub story_type: Option<String>,
    /// An array of maps specifying a CustomField ID and CustomFieldEnumValue ID that represents an
    /// assertion of some value for a CustomField.
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<Vec<crate::models::CustomFieldValueParams>>,
    /// An array of linked files attached to the story.
    #[serde(rename = "linked_files", skip_serializing_if = "Option::is_none")]
    pub linked_files: Option<Vec<crate::models::LinkedFile>>,
    /// The name of the story.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The ID of the epic the story belongs to.
    #[serde(rename = "epic_id", skip_serializing_if = "Option::is_none")]
    pub epic_id: Option<i64>,
    /// An array of external links connected to the story.
    #[serde(rename = "external_links", skip_serializing_if = "Option::is_none")]
    pub external_links: Option<Vec<String>>,
    /// The ID of the iteration the story belongs to.
    #[serde(rename = "iteration_id", skip_serializing_if = "Option::is_none")]
    pub iteration_id: Option<i64>,
    /// An array of tasks connected to the story.
    #[serde(rename = "tasks", skip_serializing_if = "Option::is_none")]
    pub tasks: Option<Vec<crate::models::StoryContentsTask>>,
    /// An array of label ids attached to the story.
    #[serde(rename = "label_ids", skip_serializing_if = "Option::is_none")]
    pub label_ids: Option<Vec<i64>>,
    /// The ID of the group to which the story is assigned.
    #[serde(rename = "group_id", skip_serializing_if = "Option::is_none")]
    pub group_id: Option<uuid::Uuid>,
    /// The ID of the workflow state the story is currently in.
    #[serde(rename = "workflow_state_id", skip_serializing_if = "Option::is_none")]
    pub workflow_state_id: Option<i64>,
    /// An array of UUIDs for any Members listed as Followers.
    #[serde(rename = "follower_ids", skip_serializing_if = "Option::is_none")]
    pub follower_ids: Option<Vec<uuid::Uuid>>,
    /// An array of UUIDs of the owners of this story.
    #[serde(rename = "owner_ids", skip_serializing_if = "Option::is_none")]
    pub owner_ids: Option<Vec<uuid::Uuid>>,
    /// The numeric point estimate of the story. Can also be null, which means unestimated.
    #[serde(rename = "estimate", skip_serializing_if = "Option::is_none")]
    pub estimate: Option<i64>,
    /// An array of files attached to the story.
    #[serde(rename = "files", skip_serializing_if = "Option::is_none")]
    pub files: Option<Vec<crate::models::UploadedFile>>,
    /// The ID of the project the story belongs to.
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i64>,
    /// The due date of the story.
    #[serde(rename = "deadline", skip_serializing_if = "Option::is_none")]
    pub deadline: Option<String>,
}

impl StoryContents {
    /// A container entity for the attributes this template should populate.
    pub fn new() -> StoryContents {
        StoryContents {
            description: None,
            entity_type: None,
            labels: None,
            story_type: None,
            custom_fields: None,
            linked_files: None,
            name: None,
            epic_id: None,
            external_links: None,
            iteration_id: None,
            tasks: None,
            label_ids: None,
            group_id: None,
            workflow_state_id: None,
            follower_ids: None,
            owner_ids: None,
            estimate: None,
            files: None,
            project_id: None,
            deadline: None,
        }
    }
}
