/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// StoryHistoryChangeAddsRemovesInt : Task IDs that have been added or removed from the Story.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StoryHistoryChangeAddsRemovesInt {
    /// The values that have been added.
    #[serde(rename = "adds", skip_serializing_if = "Option::is_none")]
    pub adds: Option<Vec<i64>>,
    /// The values that have been removed
    #[serde(rename = "removes", skip_serializing_if = "Option::is_none")]
    pub removes: Option<Vec<i64>>,
}

impl StoryHistoryChangeAddsRemovesInt {
    /// Task IDs that have been added or removed from the Story.
    pub fn new() -> StoryHistoryChangeAddsRemovesInt {
        StoryHistoryChangeAddsRemovesInt { adds: None, removes: None }
    }
}
