/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// StoryHistoryChangeOldNewUuid : The Team ID for the Story.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StoryHistoryChangeOldNewUuid {
    /// The old value.
    #[serde(rename = "old", skip_serializing_if = "Option::is_none")]
    pub old: Option<uuid::Uuid>,
    /// The new value.
    #[serde(rename = "new", skip_serializing_if = "Option::is_none")]
    pub new: Option<uuid::Uuid>,
}

impl StoryHistoryChangeOldNewUuid {
    /// The Team ID for the Story.
    pub fn new() -> StoryHistoryChangeOldNewUuid {
        StoryHistoryChangeOldNewUuid {
            old: None,
            new: None,
        }
    }
}
