/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// SyncedItem : The synced item for the story.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SyncedItem {
    /// The id used to reference an external entity.
    #[serde(rename = "external_id")]
    pub external_id: String,
    /// The url to the external entity.
    #[serde(rename = "url")]
    pub url: String,
}

impl SyncedItem {
    /// The synced item for the story.
    pub fn new(external_id: String, url: String) -> SyncedItem {
        SyncedItem { external_id, url }
    }
}
