/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UnusableEntitlementError {
    /// The tag for violating an entitlement action.
    #[serde(rename = "reason_tag")]
    pub reason_tag: ReasonTag,
    /// Short tag describing the unusable entitlement action taken by the user.
    #[serde(rename = "entitlement_tag")]
    pub entitlement_tag: String,
    /// Message displayed to the user on why their action failed.
    #[serde(rename = "message")]
    pub message: String,
}

impl UnusableEntitlementError {
    pub fn new(
        reason_tag: ReasonTag,
        entitlement_tag: String,
        message: String,
    ) -> UnusableEntitlementError {
        UnusableEntitlementError {
            reason_tag,
            entitlement_tag,
            message,
        }
    }
}

/// The tag for violating an entitlement action.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReasonTag {
    #[serde(rename = "entitlement-violation")]
    EntitlementViolation,
}

impl Default for ReasonTag {
    fn default() -> ReasonTag {
        Self::EntitlementViolation
    }
}
