/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateLabel {
    /// The new name of the label.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The new description of the label.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The hex color to be displayed with the Label (for example, \"#ff0000\").
    #[serde(
        rename = "color",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub color: Option<Option<String>>,
    /// A true/false boolean indicating if the Label has been archived.
    #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
    pub archived: Option<bool>,
}

impl UpdateLabel {
    pub fn new() -> UpdateLabel {
        UpdateLabel {
            name: None,
            description: None,
            color: None,
            archived: None,
        }
    }
}
