/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateIteration {
    /// An array of UUIDs for any Members you want to add as Followers.
    #[serde(rename = "follower_ids", skip_serializing_if = "Option::is_none")]
    pub follower_ids: Option<Vec<uuid::Uuid>>,
    /// An array of UUIDs for any Groups you want to add as Followers. Currently, only one Group association is presented in our web UI.
    #[serde(rename = "group_ids", skip_serializing_if = "Option::is_none")]
    pub group_ids: Option<Vec<uuid::Uuid>>,
    /// An array of Labels attached to the Iteration.
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<Vec<crate::models::CreateLabelParams>>,
    /// The description of the Iteration.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The name of this Iteration
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The date this Iteration begins, e.g. 2019-07-01
    #[serde(rename = "start_date", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    /// The date this Iteration ends, e.g. 2019-07-05.
    #[serde(rename = "end_date", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
}

impl UpdateIteration {
    pub fn new() -> UpdateIteration {
        UpdateIteration {
            follower_ids: None,
            group_ids: None,
            labels: None,
            description: None,
            name: None,
            start_date: None,
            end_date: None,
        }
    }
}


