/*
 * Shortcut API
 *
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateComment {
    /// The updated comment text.
    #[serde(rename = "text")]
    pub text: String,
}

impl UpdateComment {
    pub fn new(text: String) -> UpdateComment {
        UpdateComment { text }
    }
}
